local addonName, privateTable = ...
if (GetLocale() == "frFR")  then
privateTable.L = setmetatable({
	["usage1"]="'on'/'off' to enable or disable addon",
	["usage2"]="'all'/'list' to handle any quest or just specified in a list",
	["usage3"]="'loot' do not complete quests with a list of rewards or complete it and choose most expensive one of rewards",
	["all"]="ready to handle every quest",
	["list"]="only daily quests will be handled",
	["dontlootfalse"]="loot most expensive reward",
	["dontloottrue"]="do not complete quests with rewards",
	["resetbutton"]="reset",
	
	["questTypeLabel"] = "Quests to handle", 
	["questTypeAll"] = "all",
	["TrivialQuests"]="Accept 'grey' quests", 
	["questTypeList"] = "daily", 

	["lootTypeLabel"]="Quests with rewards",
	["lootTypeFalse"]="don't turn in",
	["lootTypeGreed"]="loot most expensive reward",
	["lootTypeNeed"]="loot by parameters",
	
	["tournamentLabel"]="Tournament", 
	["tournamentWrit"]="Champion's Writ", -- 46114
	["tournamentPurse"]="Champion's Purse",  -- 45724
	
	["DarkmoonTeleLabel"]="Darkmoon: teleport to the cannon",
	["DarkmoonFaireTeleport"]="Teleportologist Fozlebub",
	["DarkmoonAutoLabel"]="Darkmoon: start the game!",	
	
	["rewardtext"]="Print quest reward text",
	["autoequip"]="Equip received reward",
	["togglekey"]="Enable/disable key",
	
	['Jewelry']="Jewelry",
	["rewardlootoptions"]="Reward loot rules",
	['greedifnothing']='Greed if nothing found',
	["multiplefound"]="Multiple reward candidates found. "..ERR_QUEST_MUST_CHOOSE,
	["nosuitablefound"]="No suitable reward found. "..ERR_QUEST_MUST_CHOOSE,
	["gogreedy"]="No suitable reward found, choosing the highest value one.",
	["rewardlag"]=BUTTON_LAG_LOOT_TOOLTIP.. '. '..ERR_QUEST_MUST_CHOOSE,
	["stopitemfound"]="There is %s in rewards. Choose an item yourself.",
	},
	{__index = function(table, index) return index end})
	
privateTable.L.quests = {
-- Steamwheedle Cartel
['Faire amende honorable']={item="Etoffe runique", amount=40, currency=false},
['Combat naval']={item="Etoffe de tisse-mage", amount=40, currency=false},
['Un traitre envers la Voile sanglante']={item="Etoffe de soie", amount=40, currency=false},
['Soigner de vieilles blessures']={item="Etoffe de lin", amount=40, currency=false},
-- AV both fractions
['Ecuries vides']={donotaccept=true},

-- Alliance AV Quests
['Grappes de cristaux']={donotaccept=true},
['Ivus le Seigneur des forêts']={donotaccept=true},
["L'appel des airs - l'escadrille d'Ichman"]={donotaccept=true},
["L'appel des airs - l'escadrille de Slidore"]={donotaccept=true},
["L'appel des airs - l'escadrille de Vipore"]={donotaccept=true},
["Morceaux d'armures"]={donotaccept=true},
["Plus de morceaux d'armure !"]={donotaccept=true},
['Harnais pour béliers']={donotaccept=true},
-- Horde AV Quests
['Quelques litres de sang']={donotaccept=true},
['Lokholar le Seigneur des Glaces']={donotaccept=true},
["L'appel des airs - l'escadrille de Guse"]={donotaccept=true},
["L'appel des airs - l'escadrille de Jeztor"]={donotaccept=true},
["L'appel des airs - l'escadrille de Mulverick"]={donotaccept=true},
["Pris à l'ennemi"]={donotaccept=true},
['Plus de butin !']={donotaccept=true},
['Harnais en cuir de bélier']={donotaccept=true},
-- Timbermaw Quests
['Des plumes pour Grifleur']={item="Coiffure de plumes mort-bois", amount=5, currency=false},
['Des plumes pour Nafien']={item="Coiffure de plumes mort-bois", amount=5, currency=false},
['Plus de perles pour Salfa']={item="Perles d'esprit tombe-hiver", amount=5, currency=false},
-- Cenarion
['Les textes du Crépuscule cryptés']={item="Texte du Crépuscule crypté", amount=10, currency=false},
['Je crois encore...']={item="Texte du Crépuscule crypté", amount=10, currency=false},
-- Thorium Brotherhood
['Faveur auprès de la Confrérie, Sang de la montagne']={item="Sang de la montagne", amount=1, currency=false},
['Faveur auprès de la Confrérie, Cuir du Magma']={item="Cuir du Magma", amount=2, currency=false},
['Faveur auprès de la Confrérie, Minerai de sombrefer']={item="Minerai de sombrefer", amount=10, currency=false},
['Faveur auprès de la Confrérie, Noyau de feu']={item="Noyau de feu", amount=1, currency=false},
['Faveur auprès de la Confrérie, Noyau de lave']={item="Noyau de lave", amount=1, currency=false},
['Se faire accepter']={item="Résidu de sombrefer", amount=4, currency=false},
['Se faire encore mieux accepter']={item="Résidu de sombrefer", amount=100, currency=false},

--[[Burning Crusade]]--
--Lower City
["Plus de plumes"]={item="Plume d'arakkoa", amount=30, currency=false},
--Aldor
["De nouvelles marques de Kil'jaeden"]={item="Marque de Kil'jaeden", amount=10, currency=false},
["De nouvelles marques de Sargeras"]={item="Marque de Sargeras", amount=10, currency=false},
["Armes gangrenées"]={item="Arme gangrenée", amount=10, currency=false},
["Une marque de Kil'jaeden"]={item="Marque de Kil'jaeden", amount=1, currency=false},
["Une marque de Sargeras"]={item="Marque de Sargeras", amount=1, currency=false},
["Plus de glandes à venin"]={item="Glande à venin de croc-d'effroi", amount=8, currency=false},
--Scryer
["De nouvelles chevalières Aile-de-feu"]={item="Chevalière Aile-de-feu", amount=10, currency=false},
["De nouvelles chevalières Solfurie"]={item="Chevalière Solfurie", amount=10, currency=false},
["Tomes des arcanes"]={item="Tome des Arcanes", amount=1, currency=false},
["Une chevalière Aile-de-feu"]={item="Chevalière Aile-de-feu", amount=1, currency=false},
["Une chevalière Solfurie"]={item="Chevalière Solfurie", amount=1, currency=false},
["Plus d'yeux de basilic"]={item="Oeil de basilic trempécaille", amount=8, currency=false},
--Cenarion Exp
--Skettis
["L'évasion de Skettis"]="",
["Un déluge de feu sur Skettis"]="",
["Plus de poussière ombreuse"]={item="Poussière ombreuse", amount=6, currency=false},
--SporeGar
["Rapportez-moi un autre jardinet !"]={item="Hibiscus sanguin", amount=5, currency=false},
["Plus de spores fertiles"]={item="Spores fertiles", amount=6, currency=false},
["Plus de chapeluisants"]={item="Chapeluisant", amount=10, currency=false},
["Encore des sacs de spores"]={item="Sac de spores à maturité", amount=10, currency=false},
["Plus de vrilles !"]={item="Vrille de seigneur-tourbe", amount=6, currency=false},
["Puisque nous sommes toujours entre amis..."]="",
-- Consortium
-- Halaa
["La poudre de cristal d'Oshu'gun"]={item="Echantillon de poudre de cristal d'Oshu'gun", amount=10, currency=false},
-- Sunwell
["À la découverte de vos racines"]="",
["À la redécouverte de vos racines"]="",
["Armez les protections !"]="",
["Comportement erratique"]="",
["Déstabilisation de la Côte de Verte-branchie"]="",
["Détruire la porte"]="",
["Diversion à la Malebrèche"]="",
["Écraser la Lame de l'aube"]="",
["Intercepter des cellules de mana"]="",
["Intercepter les renforts"]="",
["L’examen multiphase"]="",
["La bataille doit continuer"]="",
["La bataille pour l'Armurerie des Confins du soleil"]="",
["Les armes d'Ata'mal"]="",
["Les frappes aériennes doivent continuer"]="",
["Les lignes telluriques et vous"]="",
["Les plans d'attaque solfurie"]="",
["Les protections du sanctum"]="",
["Maintenir le portail du Puits de soleil"]="",
["Ne vous arrêtez pas..."]="",
["On est ouvert"]="",
["On recherche : La chevalière du prince Kael'thas"]="",
["On recherche : Les sœurs du tourment"]="",
["Plus de conversions"]="",
["Prendre l'avantage"]="",
["Prendre le port"]="",
["Préparatifs"]="",
["Sang pour sang"]="",
["Tenir l'ennemi à distance"]="",
["Un don charitable"]="",
["Votre soutien indéfectible"]="",
-- Ogri'la
["Allez dompter d’autres raies de l’éther !"]="",
["Bannissez plus de démons"]="",
["Bombardez-les encore !"]="",
["Les émanations des reliques"]="",
-- Netherdrake
["Des peaux d'écorcheurs mine-néant"]="",
["Du minerai de néanticite"]="",
["Du pollen de pruinéante"]="",
["Le botterang : un traitement pour les péons bons à rien"]="",
["Le plus mortel des pièges"]="",
["Les cieux pas si cléments..."]="",
["Les cristaux de l'Aile-du-Néant"]="",
["Les dragons sont les derniers de nos soucis"]="",
["Perturber la porte du Crépuscule"]="",
["Ramasser les morceaux..."]="",
["Une mort lente"]="",
-- Fishing daily
["Celui qui s'échappa"]="",
['Filet de gangresang']="",
['Les crevettes, c’est pas pour les mauviettes']="",
['Les crocilisques sont lâchés']="",
['Succomber à vos appâts']="",
-- Cooking daily
['La vengeance est un plat...']="",
['Manalicieux']="",
['Un ragoût très épicé']="",
["Une soupe pour l'âme"]="",

--[[ WOtLK]]--
-- Kalu'ak
["Le chemin de son cœur..."]="",
["Préparer l'avenir"]="",
["Se préparer au pire"]="",
-- Oracul
["Apaiser la pierre à Pluie toute-puissante"]="",
["La maîtrise des cristaux"]="",
["La volonté des titans"]="",
["Le chant du Vent et de l'Eau"]="",
["Le pouvoir des Tout-puissants"]="",
["Un chant de fécondité"]="",
["Un chant de purification"]="",
["Un chant de réflexion"]="",
--Frenzyheart Tribe
["De drôle d'outils de guerre"]="",
["Des poulets et des varleus"]="",
["La force du sang du cœur"]="",
["La puissance de la tempête"]="",
["La puissance secrète des Frénécœurs"]="",
["Le massacre de Kartak"]="",
["Rejek : le premier sang"]="",
["Un couvre-chef de héros"]="",
--Knights of the Ebon Blade
["Descendez-les tous !"]="",
["Laisser notre marque"]="",
["Réanimez leurs cadavres !"]="",
["Trouver des informations"]="",
["Vil aime feu !"]="",
["Zone d'exclusion aérienne"]="",
--Tournament
["Allez bûcher un peu..."]="",
["Arrêter les agresseurs"]="",
["Aux portes de l'ennemi"]="",
["Ça mange quoi, un yéti, d'abord ?"]="",
["Comment retomber sur ses pattes..."]="",
["Entraînement sur le terrain"]="",
["Entre champions..."]="",
["Fil de l'hiver"]="",
["Gormok veut ses frigbolds !"]="",
["La bataille devant la citadelle"]="",
["La grande mêlée"]="",
["La menace vient d'en haut"]="",
["La miséricorde de la Lumière"]="",
["Le destin des défunts"]="",
["Le drottinn Hrothgar"]="",
["Le mandebrume Yngvar"]="",
["Le nécrorateur Kharos"]="",
["Le petit-déjeuner des champions"]="",
["L'entraînement sur le terrain d'un vaillant"]="",
["L'identification des restes"]="",
["Oh bravo, Kul !!!"]="",
["Ornolf le Balafré"]="",
["Sachez tenir vos rênes"]="",
["Secours en mer"]="",
["Sur le territoire ennemi"]="",
["Sus au kraken !"]="",
["Un don pour la cause"]="",
["Un fragment du bloc d'Ulduar"]="",
["Une arme remarquable"]="",
["Une lame digne d'un champion"]="",
--Sons of Hodir
['À la chasse aux espions']="",
["Caler la dent creuse d'Arngrim"]="",
['Chaud et froid']="",
['Planter la lance de Hodir']="",
['Polir le heaume']="",
['Souffler dans le cor de Hodir']="",
['Un tribut à Hodir']={item="Relique d'Ulduar", amount=10, currency=false},
["N'oubliez pas le permagivre !"]={item="Morceau de permagivre", amount=1, currency=false},
--The Wyrmrest Accord
['La chasse au drake']="",
['La défense du temple du Repos du ver']="",
['Un as dans notre jeu !']="",
--Valiance Expedition + Warsong Offensive
['Assaut terrestre']="",
['Attaque aérienne']="",
['Escarmouches sur la rivière Noire']="",
['Forcer le blocus']="",
["Frappez-les tant qu'ils sont à terre"]="",
['La vie ou la mort']="",
['Le sang des Élus']="",
['Pour quelques bouts de ferraille de plus...']="",
['Récupérez plus de dépêches']="",
['Réparation de déchiqueteurs']="",
['Roi de la montagne']="",
['Débordée !']="",
["Déchiquetez l'Alliance"]="",
['Le roi de la montagne']="",
['Mettez-les sur les dents']="",
['Procéder aux réparations']="",
["Que l'Alliance reste aveugle"]="",
--Jewelcrafting
['Terminer la livraison']="",
['Livraison : Amulette en jade de sang']="",
['Livraison : Bibelot du soleil changeant']="",
['Livraison : Broche du soleil pernicieux']="",
['Livraison : Figurine complexe en os']="",
['Livraison : Figurine luminescente en ivoire']="",
["Livraison : Relique de l'armure éclatante"]="",
['Réparation du collier']="",
--Fishing
['Dangereusement délicieux...']="",
['Le joyau des égouts']="",
['Le poisson-fantôme']="",
["Le sang est plus épais que l'eau"]="",
['Les bras lui en tombent']="",
--Cooking
["Convention à l'Abracadabar"]="",
['Du fromage pour Froncelor']="",
['Hot-dogs à la moutarde !']="",
['Le ragoût des égouts']="",
['Pain de viande aux champignons infusés']="",
['Une recette détrempée']="",

--[[ Cataclysm]]--
-- Firelands Invasion
["Ailes de flamme"]="",
["Au revoir, le zoziau"]="",
["Au-delà des portes de l’enfer"]="",
["Bénédiction de la nature"]="",
["Besoin... d’eau... vite..."]="",
["Braisegris"]="",
["Ça sent le roussi"]="",
["Certains l’aiment chaud"]="",
["Dans des cieux de flammes"]="",
["Dans le feu"]={donotaccept=true},
["Dans les profondeurs"]="",
["Des échos de Némésis"]="",
["Des éléments hostiles"]="",
["Dès le plus jeune âge"]="",
["Des oiseaux territoriaux"]="",
["Destruction du noyau solaire"]="",
["En plein cœur"]="",
["Entre les arbres"]="",
["Fleurs du feu"]="",
["Gare aux gardiennes"]="",
["Grands brûlés"]="",
["La colère d’une mère"]="",
["La flèche Lugubre"]={donotaccept=true},
["La puissance de Malorne"]="",
["La reine des araignées de flammes"]="",
["La saison de la plate"]="",
["Le sanctuaire ne doit pas tomber"]="",
["L'appel de la meute"]="",
["L'appel du vol"]="",
["Le retour des traîtres"]="",
["Les attise-flammes du courant du Magma"]="",
["Les chiens de guerre"]="",
["Les chiens de Shannox"]="",
["Les méthodes de Fandral"]="",
["Les protecteurs d'Hyjal"]="",
["Libérer la pression"]="",
["Nounours-ball"]="",
["Obsidium vivant"]="",
["Œuf-assez"]="",
["On se fait une toile ?"]="",
["Panser les blessures"]="",
["Pas si follet, ce feu"]="",
["Perfectionner votre hurlement"]="",
["Petit flagellant deviendra grand"]="",
["Plus dure sera la chute"]="",
["Plus ils sont gros..."]="",
["Pris par surprise"]="",
["Pyroarachnophobie"]="",
["Rage contre les flammes"]="",
["Ravitaillement pour l’autre rive"]="",
["Soulager la douleur"]="",
["Supporter la chaleur"]="",
["Un oiseau rare"]="",
["Une brèche dans les défenses"]="",
["Une croissance agressive"]="",
["Une pilule amère"]="",
["Vague de chaleur"]="",
["Voler des magmolias"]="",
["Appeler les Anciens"]={item=416, amount=125, currency=true},
["Des armes en rab"]={item=416, amount=125, currency=true},
["Remplir le puits de lune"]={item=416, amount=125, currency=true},
-- Tol Barad Peninsula
["Attention aux échardes !"]="",
["AVIS DE RECHERCHE : le contremaître Wellson"]="",
["Boulet de canon !"]="",
["C’est bon pour le moral"]="",
["Émeute à la prison"]="",
["Il faut finir le boulot"]="",
["L’archimage emprisonné"]="",
["La reprise du donjon"]="",
["La reprise du surplomb"]="",
["L'appât à crocos"]="",
["Le bac à requins"]="",
["Le bloc D"]="",
["Le capitaine P. Harris"]="",
["Le gardien"]="",
["Le lieutenant Connor"]="",
["Le nettoyage des profondeurs"]="",
["Les aimants, ça marche comment ?"]="",
["Les chaînes maudites"]="",
["Les leçons du passé"]="",
["Les Oubliés"]="",
["Les vivres d’en-bas"]="",
["Ne laissez rien derrière vous"]="",
["Nettoyage par le vide"]="",
["Qu’ils mordent le sable !"]="",
["Quand ça ne mord pas... On se sert"]="",
["SOS fantômes"]="",
["Svarnos"]="",
["Touché coulé !"]="",
["Un boulot gluant"]="",
["Un problème... de taille"]="",
["Un seul fémur vous manque..."]="",
["Un si charmant village..."]="",
["Une bonne balade en bord de mer"]="",
["Une petite décimation"]="",
["Victoire à Tol Barad"]="",
-- Therazane
["Furie fongique"]="",
["Glop, fils de Glop"]="",
["La peur de l’érosion"]="",
["Les granules"]="",
["L'impatience de la progéniture"]="",
["Perdu dans les profondeurs"]="",
["Persistance"]="",
["Sous la surface"]="",
["Tendre roche"]="",
["Une économie souterraine"]="",
--Ramkahen
["Chapardeurs"]="",
["Le feu du ciel"]="",
--Wildhammer Clan
["La route de la bière"]="",
["Le retour du seigneur de guerre Halthar"]="",
["Le secret des bièreserkers"]="",
["Rien ne se perd, rien ne se jette..."]="",
["Tenir les Gueules-de-dragon à distance"]="",
--Dragonmaw Clan
["À coups de marteau"]="",
["À mort le grand chaman"]="",
["Cours de crochet"]="",
["Encore une gueule à nourrir"]="",
["Guerre totale"]="",
--Jewelcrafter
["C'est la dernière mode !"]="",
['Grignoteur ! Non !']="",
['La gelée élémentaire']="",
['Les ogrezones amoureuses']="",
['Un présent pour Lila']="",
--Cooking Alliance
['Des côtelettes pour les sentinelles']="",
['Des galettes à la citrouille pour Penny']="",
['En souvenir des ancêtres']="",
['Il en pince pour les crabes...']="",
['Il n’y aura jamais assez de pain épicé...']="",
['La source de haggis']="",
['Le cidre du roi']="",
['Le secret pour un kimchi parfait']="",
['Les orphelins aiment aussi les macarons !']="",
['Multiplication des pains épicés']="",
['Pénurie de volaille']="",
['Retour aux fondamentaux']="",
['Un festin de pêcheur']="",
['Une petite faveur']="",
['Une tournée pour les gardes']="",
-- Cooking Horde
['Attention, ces fruits se défendent']="",
['Avec un supplément de mouches en prime ?']="",
['Bouillon de cafards']="",
['Dans le cochon, tout est bon']="",
['Des champignons « magiques »']="",
['Des écrevisses à la créole']="",
['Des envies de pignon']="",
['Escargots à gogo']="",
['La farine de maïs']="",
['Le pain épicé de Mulgore']="",
['Les portions parfaites']="",
['Même les voleurs ont faim']="",
['Tous les champi du monde']="",
['Un bouquet de lys']="",
['Voler les siens']="",
--Fishing Alliance
['Du poisson pour Glapie']="",
['Heureux comme une palourde dans l’eau']="",
['L’appât-matic gnome']="",
['La pêche en eau froide']="",
['Le doré jaune']="",
['Le pendentif de la sœur']="",
['Les chutes du Tonnerre']="",
['Les homards des rochers']="",
['Pour la postérité']="",
['Réapprovisionnement']="",
['Un appât vivant']="",
['Un en-cas fuyant']="",
['Un plat traditionnel']="",
['Un ver, ça va. Trois vers...']="",
['Une grande goulée']="",
--Fishing Horde
['À la pêche aux palourdes, lourdes, lourdes...']="",
["Dépôt d'ordures interdit"]="",
['Des efforts stupéfiants']="",
['Empoissonner l’étang']="",
['Ferrer le brochet']="",
['J’ai envie d’écrevisses']="",
['La pêche à la tête']="",
['La terreur des têtards titanesques']="",
['Le monstre des douves !']="",
['Le seigneur de l’anneau']="",
['Le temps des limons']="",
['Les prédateurs de l’étang']="",
['Une occasion en or']="",
['Une prise furieuse']="",
['Verroteries rutilantes']="",
--Darkmoon Faire
["Les petits s'amusent aussi"] = {item=393, amount=15, currency=true},
['Cible : tortue']="",
['Commandant de chariotte']="",
['Il est temps de cogner']="",
['Il tire et... il marque !']="",
['Le boulet de canon humanoïde']="",
--Love is in the Air
['Bombardement de bonbons']="",
['Détrôner la Royale']="",
["Un cadeau pour la grande prêtresse d'Élune"]="",
['Un cadeau pour la reine banshee']="",
['Un cadeau pour le chef de guerre']="",
['Un cadeau pour le grand chef']="",
['Un cadeau pour le prophète']="",
['Un cadeau pour le roi de Hurlevent']="",
["Un cadeau pour le seigneur régent de Quel'Thalas"]="",
['Un cadeau pour un seigneur de Forgefer']="",
['Un nuage de Cologne classieuse']="",
['Une parfaite petite pointe de parfum']="",
['Vous êtes servi']="",
--Noblegarden
['Collecteurs du printemps']="",
['La grande chasse aux œufs']="",
['Mettez tous vos œufs dans ce panier']="",
['Récolteurs du printemps']="",
--Midsummer Fire Festival
['Attraper plus de torches']="",
['Contre-attaquer']="",
['Lancer plus de torches']="",
["L'invocation d'Ahune"]="",
--Stranglethorn Fishing Extravaganza
['Apprenti pêcheur']="",
['Maître pêcheur']="",
["Poisson rare : le scalaire de Keefer"]="",
['Poisson rare : le talang dezien']="",
["Poisson rare : le tassergal à dos rayé"]="",
--Kalu'ak Fishing Derby
['Plus de chance la prochaine fois']="",
["Le tournoi de pêche kalu'ak"]="",
}
end